name: Release
on: workflow_dispatch
jobs:
  build-project:
    name: Build Python project
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller main.py --onefile -w
          
      - name: Upload Assetd
        uses: actions/upload-artifact@v3
        with:
          name: site-build
          path: dist/main.exe
          
      - name: Download site content
        uses: actions/download-artifact@v2
        with:
          name: site-build
          
      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: site.zip
          
      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          
      - name: Upload asset to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./site.zip
          asset_name: site-v${{ github.run_number }}.zip
          asset_content_type: application/zip  
