name: Release
on: workflow_dispatch

jobs:
  build-project:
    name: Build Python project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    outputs:
      artifact-path: ${{ steps.upload-artifact.outputs.artifact_path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller main.py --onefile -w

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: site-build
          path: dist/main.exe

  distribute-project:
    name: Distribute project to GitHub Releases
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download site content
        uses: actions/download-artifact@v2
        with:
          name: site-build
          path: dist/

      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}

      - name: Upload Windows asset to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ${{ needs.build-project.outputs.artifact-path }}
          asset_name: windows-v${{ github.run_number }}.zip
          asset_content_type: application/zip

      - name: Upload Linux asset to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: dist/site.zip
          asset_name: linux-v${{ github.run_number }}.zip
          asset_content_type: application/zip

      - name: Upload Mac asset to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: dist/site.zip
          asset_name: mac-v${{ github.run_number }}.zip
          asset_content_type: application/zip
